---
title: 'Resume'
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
---

```{r, message= FALSE, warning = FALSE, echo = FALSE}
library(tidyverse)
library(rmarkdown)     # You need this library to run this template.
library(mikedown)

```

------------------------------------------------------------------------

# **ANGUS WATTERS**

#### 2786 Ben Lomond Dr. Santa Barbara, CA 93105\| 805.895.1590\| [anguswatters\@gmail.com](mailto:anguswatters@gmail.com){.email}

<br>

**WORK OBJECTIVE**
------------------------------------------------------------------------

I am a data scientists and data engineer, working remotely for Lynker Technologies out of Santa Barbara, CA. I am passionate about all things data science, programming, and machine learning. I specialize in spatial data collection, aggregation, statistical analysis, and visualization. I have experience creating interactive R Shiny Dashboards, R packages, implementing machine learning model workflows, and deploying software solutions for clients through REST API services. I have a thirst for knowledge and try to continue my growth and education each day. I believe to be a responsible employee one must tackle every task with diligence and care.  
<br> 

**EDUCATION** 
------------------------------------------------------------------------

#### **UNIVERSITY OF CALIFORNIA, SANTA BARBARA --** (2019 -- 2021)

##### *B.A. in Geography with an Emphasis in Geographic Information Science*

<br>

#### **SANTA BARBARA CITY COLLEGE --** (2016- 2018)

<br>

**RELEVANT EXPERIENCE**
------------------------------------------------------------------------

#### **Lynker Technologies**, Remote out of Santa Barbara, CA<br/> ***Spatial Data Scientist***, **(2021 - present)**

-   Wrangling, cleaning, and management of client data
-   Developing hydrologic/spatial machine learning model workflows,
    starting with data acquisition and ending with a production ready
    analytic model that meets client needs
-   Developing and deploying interactive data visualization technologies (R Shiny) to view incremental progress on tasks or as a final product to clients.
-   Creating REST API services for clients
-   R/Python Package development
-   Creating and maintaining project code bases through GitHub
-   Presenting technical write ups and documentation for the client to
    convey results or work in progress

<br>

#### **US GROUNDWATER RESEARCH**, University of California, Santa Barbara, CA<br/>***Research assistant***, [Professor Perrone, Debra](https://www.es.ucsb.edu/debra-perrone) **(2019 - 2021)**

-   Analyzing spatial and non-spatial US Geological Survey and state
    groundwater data in R
-   Focus on the analysis of groundwater well depths and pumping
-   Analysis of the results of different state level sustainable
    groundwater management approaches

<br>

#### **FLOOD MAPPING RESEARCH**, University of California, Santa Barbara, CA<br/>***Research assistant***, [Mike Johnson, UCSB PhD candidate](https://mikejohnson51.github.io/) **(2020 - present)**

-   Mapping terrain-based flood extents, with the goal of produce a
    continental flood map that can be used in real time for Emergency
    Medical Services specifically comparing known FEMA flood extents
    with a 'bucket', Height Above Nearest Drainage model
-   Comparison of known FEMA flood extents with a 'bucket' HAND model
    using raster data

<br>

#### **INSTRUCTIONAL ASSISTANT**, University of California, Santa Barbara, CA<br/>***ENVS 193*** [Profesor Perrone, Debra](https://www.es.ucsb.edu/debra-perrone) **(Winter Quarter 2021)**

-   I am an instructional assistant in a class focused on teaching
    students how to organize, clean, manipulate and analyze large
    hydrological data sets using R
-   With my expertise in R, I provide technical programming support,
    contribute to writing labs, and leading portions of labs <br>\
    <br> <br> <br>

**SKILLS + INTERESTS**
------------------------------------------------------------------------

##### **Skills:**
-   [**Data Science Portfolio**](https://anguswg-ucsb.github.io/projects.html)
-   Highly proficient using R/Python as a tool for data science and GIS:
    -   Cleaning, organizing, aggregating, and analyzing both spatial
        and non-spatial data
    -   Implementing Machine Learning Models from data ingestion to deployment
    -   Using various ML modeling frameworks (Decision trees, SVMs, Neural Networks, etc.)
    -   Processing text data for use in NLP ML models
    -   Creating R Shiny interactive dashboards
    -   Creating data visualizations in R/Python
    -   REST API Development
    -   R/Python package development
    -   Creating reproducible code and workflows in R/Python
    -   Working in GitHub repositories and maintaining clean and up-to-date code bases.
    -   Web scraping
    -   Working with large, 'messy' government data sets, shape files,
        and time series data
-   Experienced using SQL
-   Proficiency in AWS core services (S3, EC2, Lambda, DynamoDB, SQS, SNS, IAM, API Gateway)
-   Experienced in creating Docker images
-   Experienced deploying docker containers to Cloud Infrastructure Providers (AWS, DigitalOcean). 
-   Progressing through AWS Solutions Architect certificate
-   Able to work with CSS and HTML code
-   Proficient in Microsoft Office
-   Experienced using QGIS, ArcGIS Pro, ArcGIS Online

##### **Interests:**

-   I enjoy an active lifestyle (running, biking, swimming, rowing,
    kayaking), gardening, playing card/board games, drawing, and spending time with friends and family.

<br> <br> <br>

**OTHER WORK EXPERIENCE**
------------------------------------------------------------------------
#### **SANTA BARBARA RUNNING**, Santa Barbara, CA<br/>*Sales Representative* **(2019 - present)**

-   Provided information and options on shoes based on an individual's
    goals and needs
-   Comfortably multitask, ensuring optimal response to customers'
    requests

<br>

#### **GALLUP & STRIBLING ORCHIDS**, Carpinteria, CA<br/>*Sales Representative* **(2018)**

-   Provided exceptional customer service while processing phone orders
-   Provided support during hectic Mother's Day season
-   Collaborated with the flower production floor and truck drivers
    receiving orders, maintaining clear communication between all
    parties

<br>

#### **THE GARDEN MARKET**, Carpinteria, CA<br/>*Cashier & Server* **(2017)**

-   Provided friendly and efficient customer service; striving to give
    customers a positive dining experience by attending to their needs
    promptly and enthusiastically

<br>

#### **SORAA INC.**, Goleta, CA<br/>*Intern* **(Spring 2015)**

-   Gained an introduction into the production of GaN crystals used in
    LEDs and contributed in organizing data collected from GaN
    production runs in Excel files.

<br>\
<br> <br>

## **VOLUNTEER EXPERIENCE**

------------------------------------------------------------------------

#### **SANTA BARBARA FOODBANK'S BACKYARD BOUNTY**<br/>*Community Outreach & volunteer fundraiser* **(2014 -- 2018)**

-   tasked with leading groups into local residences to harvest fruits
    and vegetables which are then distributed back to the community by
    the Foodbank.

<br>

#### **LAGUNA BLANCA SPORTS DRIVE**<br/>*Volunteer* **(2011-2015)**

-   Organized and oversaw the collection of used sports equipment which
    were donated to the Goleta Boys & Girls Club.

<br> <br> <br>

## **REFERENCES**

------------------------------------------------------------------------
-   Mike Johnson, coworker, Lead Data Scientist at Lynker - [mike.johnson\@noaa.gov](mailto:mike.johnson@noaa.gov){.email}
-   Debra Perrone, UCSB Bren School of ESM, Assistant Professor -
    [perrone\@ucsb.edu](mailto:perrone@ucsb.edu){.email}\
-   Dan Brown, personal reference, Supply Chain Automation at AWS - [dbrwnib\@amazon.com](mailto:dbrwnib@amazon.com){.email}
-   Joe DeVreese, Santa Barbara Running -- (805) 729-0138
-   Sherrie Todd, The Garden Market -- (805) 708-6428
